# Site settings
title: Philosophy for a Type 1 Civilization
email: dylan.massell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The meaning of life is to give meaning to your life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dylanmassell
github_username:  danarch

# Build settings
markdown: kramdown
