# Site settings
title: Dylan Massell
email: dylan.massell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What I have found the meaning of life to be, is simply to give meaning to life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dylanmassell
github_username:  danarch

# Build settings
markdown: kramdown
