# Site settings
title: Dylan Massell
email: dylan.massell@gmail.com
tagline: Pursuing a philosophy for programming.
description: > # this means to ignore newlines until "baseurl:"
  A webspace dedicated to showcasing my work and experience. Contact me for any oppurtunities you might have.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dylanmassell.net" # the base hostname & protocol for your site
googleplus_username: +DylanMassell
linkedin_username: dylan-massell
twitter_username: dylanmassell
github_username:  danarch

# Build settings
markdown: kramdown
sass:
  # loading path from site root
  # default to _sass
  sass_dir: assets/bootstrap/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed
